apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: revcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: karandeepsingh15/revcart.gateway:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: revcart-secrets
                  key: jwt-secret
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: revcart
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
