apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: revcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: karandeepsingh15/revcart.product-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8082
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: revcart-config
                  key: product-db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: revcart-config
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: revcart-secrets
                  key: db-password
            - name: USER_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: revcart-config
                  key: user-timezone
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: revcart
spec:
  selector:
    app: product-service
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
