apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-inventory
  namespace: revcart
spec:
  serviceName: postgres-inventory-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres-inventory
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "inventory_db"
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: revcart-config
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: revcart-secrets
                  key: db-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory-headless
  namespace: revcart
spec:
  clusterIP: None
  selector:
    app: postgres-inventory
  ports:
    - port: 5432
      targetPort: 5432
