server:
  port: 8086
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5438/cart_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          product-service:
            connectTimeout: 2000
            readTimeout: 5000
services:
  product:
    url: http://localhost:8082

resilience4j:
  retry:
    retryAspectOrder: 2
    instances:
      product-service:
        max-attempts: 3
        wait-duration: 2s
        ignore-exceptions:
          - com.revcart.cart_service.exception.ValidationException
          - com.revcart.cart_service.exception.ProductNotAvailableException
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      product-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - com.revcart.cart_service.exception.ValidationException
          - com.revcart.cart_service.exception.ProductNotAvailableException

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
